INSERT INTO users (username, role, password) VALUES
('user1', 'ROLE_USER', '$2a$10$bF.JhIykRbsPg8gxKfWZZu3OMloVeGRmRdS8C8GV.lDnXJlyMoNOq');

INSERT INTO shopping_cart (user_id) VALUES
(1);

insert into product_category(title, description) values
    ('смартфоны', 'Мобильные телефоны различных брендов');
insert into product_category(title, description) values
    ('умные часы', 'Умные часы и фитнес-браслеты');
insert into product_category(title, description) values
    ('аксессуары', 'Наушники и зарядки по 100 рублей на андроид и на айфон');

INSERT INTO product (title, description, price, quantity, product_category_id) VALUES
('Xiaomi Redmi Note 14', '256 Гб LTE полуночный черный', 22990.00, 459, 1),
('Samsung Galaxy S23', '128 Гб 5G чёрный', 79990.00, 210, 1),
('iPhone 15 Pro', '256 Гб 5G титановый серый', 124990.00, 185, 1),
('Realme 11 Pro+', '512 Гб LTE солнечное золото', 34990.00, 320, 1),
('OnePlus Nord 3', '256 Гб 5G серый туман', 42990.00, 150, 1),
('Часы HUAWEI Watch D2 Luca', 'белые', 28990.00, 6743, 2),
('Apple Watch Ultra 2', 'титановый корпус', 79990.00, 1250, 2),
('Samsung Galaxy Watch6 Classic', 'черный, 47mm', 34990.00, 2890, 2),
('Xiaomi Watch 2 Pro', 'серебряные', 27990.00, 4321, 2),
('Портативная акустическая система JBL GO 3', 'Blue', 3590.00, 821, 3),
('Переходник Apple с Lightning', '(8-pin) на Jack 3,5mm MMX62ZM/A White', 1490.00, 236, 3),
('Держатель автомобильный RedLine HOL-12', 'гибкая штанга универсальный Black', 449.00, 785, 3);

CREATE TABLE cart_items (
  quantity INTEGER NOT NULL,
   cart_id BIGINT,
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   product_id BIGINT,
   CONSTRAINT cart_items_pkey PRIMARY KEY (id)
);

CREATE TABLE order_items (
  quantity INTEGER NOT NULL,
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   order_id BIGINT,
   product_id BIGINT,
   CONSTRAINT order_items_pkey PRIMARY KEY (id)
);

CREATE TABLE orders (
  order_amount FLOAT8 NOT NULL,
   delivery_time TIMESTAMP WITHOUT TIME ZONE,
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   user_id BIGINT NOT NULL,
   address VARCHAR(255) NOT NULL,
   delivery_type VARCHAR(255) NOT NULL,
   status VARCHAR(255) NOT NULL,
   CONSTRAINT orders_pkey PRIMARY KEY (id)
);

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   password VARCHAR(255) NOT NULL,
   role VARCHAR(255) NOT NULL,
   username VARCHAR(255) NOT NULL,
   CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE personal_info (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   user_id BIGINT,
   card_number VARCHAR(255),
   phone_number VARCHAR(255),
   CONSTRAINT personal_info_pkey PRIMARY KEY (id)
);

CREATE TABLE product_category (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   description VARCHAR(255),
   title VARCHAR(255) NOT NULL,
   CONSTRAINT product_category_pkey PRIMARY KEY (id)
);

CREATE TABLE shopping_cart (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   user_id BIGINT,
   CONSTRAINT shopping_cart_pkey PRIMARY KEY (id)
);

ALTER TABLE users ADD CONSTRAINT users_username_key UNIQUE (username);

ALTER TABLE personal_info ADD CONSTRAINT personal_info_user_id_key UNIQUE (user_id);

ALTER TABLE product_category ADD CONSTRAINT product_category_title_key UNIQUE (title);

ALTER TABLE shopping_cart ADD CONSTRAINT shopping_cart_user_id_key UNIQUE (user_id);

CREATE TABLE product (
  price FLOAT8 NOT NULL,
   quantity INTEGER NOT NULL,
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   product_category_id BIGINT,
   description VARCHAR(255),
   title VARCHAR(255) NOT NULL,
   CONSTRAINT product_pkey PRIMARY KEY (id)
);

CREATE TABLE product_filters (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   description VARCHAR(255),
   title VARCHAR(255),
   CONSTRAINT product_filters_pkey PRIMARY KEY (id)
);

ALTER TABLE personal_info ADD CONSTRAINT fk2ooyctbfk03w21tuk720ixnqh FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE orders ADD CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE order_items ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES orders (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE product ADD CONSTRAINT fkcwclrqu392y86y0pmyrsi649r FOREIGN KEY (product_category_id) REFERENCES product_category (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE cart_items ADD CONSTRAINT fkkwkexjephx1g1xu4e6x99qq5m FOREIGN KEY (cart_id) REFERENCES shopping_cart (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE cart_items ADD CONSTRAINT fkl7je3auqyq1raj52qmwrgih8x FOREIGN KEY (product_id) REFERENCES product (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE order_items ADD CONSTRAINT fklf6f9q956mt144wiv6p1yko16 FOREIGN KEY (product_id) REFERENCES product (id) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE shopping_cart ADD CONSTRAINT fkr1irjigmqcpfrvggavnr7vjyv FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE NO ACTION;